### ISSUE TITLE
Problème de finalisation de l'installation

### ISSUE THREAD

**Issue by AliBenzenoue26** [Evarisk/bibliotheque-media-risque#108]
je viens d'installer le logiciel ''DigiRisk" et quand je commence la configuration en insérant le nom de l'entreprise ça me donne l'erreur suivante : 

Fatal error: Uncaught Error: Call to undefined function isModEnabled() in C:\dolibarr\www\dolibarr\htdocs\custom\digiriskdolibarr\core\modules\modDigiriskDolibarr.class.php:850 Stack trace: #0 C:\dolibarr\www\dolibarr\htdocs\core\lib\admin.lib.php(1382): modDigiriskdolibarr->__construct(Object(DoliDBMysqli)) #1 C:\dolibarr\www\dolibarr\htdocs\admin\company.php(77): activateModulesRequiredByCountry('DZ') #2 {main} thrown in C:\dolibarr\www\dolibarr\htdocs\custom\digiriskdolibarr\core\modules\modDigiriskDolibarr.class.php on line 850

y-t-il quelqu'un pour m'aider à resoudre ce problème ?

**Comment by lmag** [comment]
Bonjour,

Il serait préférable de demander de l aide sur le forum dolibarr dans la section digirisk.

Bien cordialement

**Comment by lmag** [comment]
Voici le lien @AliBenzenoue26 
https://www.dolibarr.fr/forum/t/module-digirisk-document-unique/37119/27
