### ISSUE TITLE
Manque pictos

### ISSUE THREAD

**Issue by lmag** [Evarisk/bibliotheque-media-risque#17]
Homme pour les symptomes
Postillons entre 2 personnes

**Comment by Remi-tz** [comment]
![pistolet-thermometre](https://user-images.githubusercontent.com/61967469/78037148-72075700-736b-11ea-98b8-992225ff9c98.png)
![symptome](https://user-images.githubusercontent.com/61967469/78037151-73388400-736b-11ea-85dc-da2d4b724009.png)
![distance](https://user-images.githubusercontent.com/61967469/78037152-73388400-736b-11ea-944e-41b35409dc47.png)

**Comment by Remi-tz** [comment]
![pistolet-thermo-v2](https://user-images.githubusercontent.com/61967469/78041796-7c2c5400-7371-11ea-94a6-a048c2d7b709.png)
![distances-v2](https://user-images.githubusercontent.com/61967469/78041799-7d5d8100-7371-11ea-9007-9199985f27a4.png)

**Comment by lmag** [comment]
C'est Super
Tu peux les passer en PR
